
- name: remove playbook
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/env
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: install python packages
      pip:
        name:
        - boto
        - boto3
        - botocore

    - name: remove server instance
      include_role:
        name: container
      vars:
        state: absent

    - name: remove networking
      include_role:
        name: networking
      vars:
        state: absent
    
    - name: delete ip file
      ansible.builtin.file:
        path: ../ip
        state: absent
