
- name: create server
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/env
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:
    
    - name: Install python packages
      pip:
        name:
        - boto
        - boto3
        - botocore

    - name: create networking
      include_role:
        name: networking 

    - name: create instance
      include_role:
        name: container
    
    - name: ip to file
      ansible.builtin.copy:
        content: "{{instance_ip}}"
        dest: ../ip

     
- name: deploy
  hosts: app
  user: ubuntu
  become: True
  gather_facts: True
  vars_files:
    - group_vars/env
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: deploy app
      include_role:
        name: connect

    - debug: msg="done at {{ ansible_date_time.iso8601 }}"
