
name: create/remove

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: "choose playbook"
        required: true
        default: "create"
        type: choice
        options:
        - create
        - remove

jobs:
  CreateDockerImage:
    runs-on: ubuntu-latest
    if: inputs.playbook == 'create'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Create Image
        run: docker build -t ${{ secrets.DOCKER_USER}}/myapp:latest .
      
      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/myapp:latest

  playbook:
    runs-on: ubuntu-latest
    env:
      playbook: "playbook_${{inputs.playbook}}"
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_USER }}
          aws-secret-access-key: ${{ secrets.AWS_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          known_hosts: 'none'

      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ env.playbook }}.yaml
          directory: ./ansible
      
      - name: print ip
        if: ${{ inputs.playbook == 'create' }}
        run: |
          cat ip

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
