# This workflow updates the instance

name: Update Instance

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
     - 'src/**'


jobs:
  updateDockerImage:
    runs-on: ubuntu-latest 
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker image upgrade
        run: docker build -t ${{ secrets.DOCKER_USER}}/myapp:latest .
      
      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/myapp:latest
  
  InstanceUpd:
    runs-on: ubuntu-latest 
    needs: updateDockerImage
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set ip env var
        run: |
          IP=$(cat server_ip.txt)
          echo "INSTANCE_IP=$IP" >> $GITHUB_ENV
      
      - name: Updated instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            sudo docker stop myapp
            sudo docker rm myapp
            sudo docker rmi ${{ secrets.DOCKER_USER }}/myapp
            sudo docker pull ${{ secrets.DOCKER_USER }}/myapp
            sudo docker run --name myapp -d -p 80:3000 ${{ secrets.DOCKER_USER }}/myapp


      
